//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Licenses_Generator_DBFirst.HelperClasses;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Action'.<br/><br/></summary>
	[Serializable]
	public partial class ActionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private LicenseRequestEntity _licenseRequest;
		private UserEntity _user;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ActionEntityStaticMetaData _staticMetaData = new ActionEntityStaticMetaData();
		private static ActionRelations _relationsFactory = new ActionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name LicenseRequest</summary>
			public static readonly string LicenseRequest = "LicenseRequest";
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ActionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ActionEntityStaticMetaData()
			{
				SetEntityCoreInfo("ActionEntity", InheritanceHierarchyType.None, false, (int)Licenses_Generator_DBFirst.EntityType.ActionEntity, typeof(ActionEntity), typeof(ActionEntityFactory), false);
				AddNavigatorMetaData<ActionEntity, LicenseRequestEntity>("LicenseRequest", "Actions", (a, b) => a._licenseRequest = b, a => a._licenseRequest, (a, b) => a.LicenseRequest = b, Licenses_Generator_DBFirst.RelationClasses.StaticActionRelations.LicenseRequestEntityUsingRequestIdStatic, ()=>new ActionRelations().LicenseRequestEntityUsingRequestId, null, new int[] { (int)ActionFieldIndex.RequestId }, null, true, (int)Licenses_Generator_DBFirst.EntityType.LicenseRequestEntity);
				AddNavigatorMetaData<ActionEntity, UserEntity>("User", "Actions", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, Licenses_Generator_DBFirst.RelationClasses.StaticActionRelations.UserEntityUsingUserIdStatic, ()=>new ActionRelations().UserEntityUsingUserId, null, new int[] { (int)ActionFieldIndex.UserId }, null, true, (int)Licenses_Generator_DBFirst.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ActionEntity()
		{
		}

		/// <summary> CTor</summary>
		public ActionEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ActionEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ActionEntity</param>
		public ActionEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Action which data should be fetched into this Action object</param>
		public ActionEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Action which data should be fetched into this Action object</param>
		/// <param name="validator">The custom validator object for this ActionEntity</param>
		public ActionEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ActionEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'LicenseRequest' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoLicenseRequest() { return CreateRelationInfoForNavigator("LicenseRequest"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ActionEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ActionRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'LicenseRequest' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathLicenseRequest { get { return _staticMetaData.GetPrefetchPathElement("LicenseRequest", CommonEntityBase.CreateEntityCollection<LicenseRequestEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The Comments property of the Entity Action<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."comments".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Comments
		{
			get { return (System.String)GetValue((int)ActionFieldIndex.Comments, true); }
			set	{ SetValue((int)ActionFieldIndex.Comments, value); }
		}

		/// <summary>The Id property of the Entity Action<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)ActionFieldIndex.Id, true); }
			set { SetValue((int)ActionFieldIndex.Id, value); }		}

		/// <summary>The RequestId property of the Entity Action<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."RequestId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 RequestId
		{
			get { return (System.Int32)GetValue((int)ActionFieldIndex.RequestId, true); }
			set	{ SetValue((int)ActionFieldIndex.RequestId, value); }
		}

		/// <summary>The Type property of the Entity Action<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."type".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Type
		{
			get { return (System.String)GetValue((int)ActionFieldIndex.Type, true); }
			set	{ SetValue((int)ActionFieldIndex.Type, value); }
		}

		/// <summary>The UserId property of the Entity Action<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."UserId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UserId
		{
			get { return (System.Int32)GetValue((int)ActionFieldIndex.UserId, true); }
			set	{ SetValue((int)ActionFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'LicenseRequestEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual LicenseRequestEntity LicenseRequest
		{
			get { return _licenseRequest; }
			set { SetSingleRelatedEntityNavigator(value, "LicenseRequest"); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Licenses_Generator_DBFirst
{
	public enum ActionFieldIndex
	{
		///<summary>Comments. </summary>
		Comments,
		///<summary>Id. </summary>
		Id,
		///<summary>RequestId. </summary>
		RequestId,
		///<summary>Type. </summary>
		Type,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Licenses_Generator_DBFirst.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Action. </summary>
	public partial class ActionRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ActionEntity and LicenseRequestEntity over the m:1 relation they have, using the relation between the fields: Action.RequestId - LicenseRequest.Id</summary>
		public virtual IEntityRelation LicenseRequestEntityUsingRequestId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "LicenseRequest", false, new[] { LicenseRequestFields.Id, ActionFields.RequestId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ActionEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Action.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, ActionFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticActionRelations
	{
		internal static readonly IEntityRelation LicenseRequestEntityUsingRequestIdStatic = new ActionRelations().LicenseRequestEntityUsingRequestId;
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new ActionRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticActionRelations() { }
	}
}
