//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Licenses_Generator_DBFirst.HelperClasses;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Address'.<br/><br/></summary>
	[Serializable]
	public partial class AddressEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private ClientEntity _client;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static AddressEntityStaticMetaData _staticMetaData = new AddressEntityStaticMetaData();
		private static AddressRelations _relationsFactory = new AddressRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Client</summary>
			public static readonly string Client = "Client";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AddressEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AddressEntityStaticMetaData()
			{
				SetEntityCoreInfo("AddressEntity", InheritanceHierarchyType.None, false, (int)Licenses_Generator_DBFirst.EntityType.AddressEntity, typeof(AddressEntity), typeof(AddressEntityFactory), false);
				AddNavigatorMetaData<AddressEntity, ClientEntity>("Client", "Addresses", (a, b) => a._client = b, a => a._client, (a, b) => a.Client = b, Licenses_Generator_DBFirst.RelationClasses.StaticAddressRelations.ClientEntityUsingClientIdStatic, ()=>new AddressRelations().ClientEntityUsingClientId, null, new int[] { (int)AddressFieldIndex.ClientId }, null, true, (int)Licenses_Generator_DBFirst.EntityType.ClientEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AddressEntity()
		{
		}

		/// <summary> CTor</summary>
		public AddressEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AddressEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AddressEntity</param>
		public AddressEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Address which data should be fetched into this Address object</param>
		public AddressEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Address which data should be fetched into this Address object</param>
		/// <param name="validator">The custom validator object for this AddressEntity</param>
		public AddressEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AddressEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Client' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoClient() { return CreateRelationInfoForNavigator("Client"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AddressEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AddressRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Client' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathClient { get { return _staticMetaData.GetPrefetchPathElement("Client", CommonEntityBase.CreateEntityCollection<ClientEntity>()); } }

		/// <summary>The Address property of the Entity Address<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."address".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Address
		{
			get { return (System.String)GetValue((int)AddressFieldIndex.Address, true); }
			set	{ SetValue((int)AddressFieldIndex.Address, value); }
		}

		/// <summary>The City property of the Entity Address<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."city".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String City
		{
			get { return (System.String)GetValue((int)AddressFieldIndex.City, true); }
			set	{ SetValue((int)AddressFieldIndex.City, value); }
		}

		/// <summary>The ClientId property of the Entity Address<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."ClientId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 ClientId
		{
			get { return (System.Int32)GetValue((int)AddressFieldIndex.ClientId, true); }
			set	{ SetValue((int)AddressFieldIndex.ClientId, value); }
		}

		/// <summary>The Governorate property of the Entity Address<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."governorate".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Governorate
		{
			get { return (System.String)GetValue((int)AddressFieldIndex.Governorate, true); }
			set	{ SetValue((int)AddressFieldIndex.Governorate, value); }
		}

		/// <summary>The Id property of the Entity Address<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)AddressFieldIndex.Id, true); }
			set { SetValue((int)AddressFieldIndex.Id, value); }		}

		/// <summary>The Zip property of the Entity Address<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."Zip".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Zip
		{
			get { return (System.String)GetValue((int)AddressFieldIndex.Zip, true); }
			set	{ SetValue((int)AddressFieldIndex.Zip, value); }
		}

		/// <summary>Gets / sets related entity of type 'ClientEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ClientEntity Client
		{
			get { return _client; }
			set { SetSingleRelatedEntityNavigator(value, "Client"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Licenses_Generator_DBFirst
{
	public enum AddressFieldIndex
	{
		///<summary>Address. </summary>
		Address,
		///<summary>City. </summary>
		City,
		///<summary>ClientId. </summary>
		ClientId,
		///<summary>Governorate. </summary>
		Governorate,
		///<summary>Id. </summary>
		Id,
		///<summary>Zip. </summary>
		Zip,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Licenses_Generator_DBFirst.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Address. </summary>
	public partial class AddressRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AddressEntity and ClientEntity over the m:1 relation they have, using the relation between the fields: Address.ClientId - Client.Id</summary>
		public virtual IEntityRelation ClientEntityUsingClientId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Client", false, new[] { ClientFields.Id, AddressFields.ClientId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAddressRelations
	{
		internal static readonly IEntityRelation ClientEntityUsingClientIdStatic = new AddressRelations().ClientEntityUsingClientId;

		/// <summary>CTor</summary>
		static StaticAddressRelations() { }
	}
}
