//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Licenses_Generator_DBFirst.HelperClasses;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'dboAddress'.<br/><br/></summary>
	[Serializable]
	public partial class dboAddressEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static dboAddressEntityStaticMetaData _staticMetaData = new dboAddressEntityStaticMetaData();
		private static dboAddressRelations _relationsFactory = new dboAddressRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class dboAddressEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public dboAddressEntityStaticMetaData()
			{
				SetEntityCoreInfo("dboAddressEntity", InheritanceHierarchyType.None, false, (int)Licenses_Generator_DBFirst.EntityType.dboAddressEntity, typeof(dboAddressEntity), typeof(dboAddressEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static dboAddressEntity()
		{
		}

		/// <summary> CTor</summary>
		public dboAddressEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public dboAddressEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this dboAddressEntity</param>
		public dboAddressEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboAddress which data should be fetched into this dboAddress object</param>
		public dboAddressEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboAddress which data should be fetched into this dboAddress object</param>
		/// <param name="validator">The custom validator object for this dboAddressEntity</param>
		public dboAddressEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected dboAddressEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this dboAddressEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static dboAddressRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Address property of the Entity dboAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."address".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Address
		{
			get { return (System.String)GetValue((int)dboAddressFieldIndex.Address, true); }
			set	{ SetValue((int)dboAddressFieldIndex.Address, value); }
		}

		/// <summary>The City property of the Entity dboAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."city".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String City
		{
			get { return (System.String)GetValue((int)dboAddressFieldIndex.City, true); }
			set	{ SetValue((int)dboAddressFieldIndex.City, value); }
		}

		/// <summary>The ClientId property of the Entity dboAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."ClientId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 ClientId
		{
			get { return (System.Int32)GetValue((int)dboAddressFieldIndex.ClientId, true); }
			set	{ SetValue((int)dboAddressFieldIndex.ClientId, value); }
		}

		/// <summary>The Governorate property of the Entity dboAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."governorate".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Governorate
		{
			get { return (System.String)GetValue((int)dboAddressFieldIndex.Governorate, true); }
			set	{ SetValue((int)dboAddressFieldIndex.Governorate, value); }
		}

		/// <summary>The Id property of the Entity dboAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)dboAddressFieldIndex.Id, true); }
			set { SetValue((int)dboAddressFieldIndex.Id, value); }		}

		/// <summary>The Zip property of the Entity dboAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Address"."Zip".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Zip
		{
			get { return (System.String)GetValue((int)dboAddressFieldIndex.Zip, true); }
			set	{ SetValue((int)dboAddressFieldIndex.Zip, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Licenses_Generator_DBFirst
{
	public enum dboAddressFieldIndex
	{
		///<summary>Address. </summary>
		Address,
		///<summary>City. </summary>
		City,
		///<summary>ClientId. </summary>
		ClientId,
		///<summary>Governorate. </summary>
		Governorate,
		///<summary>Id. </summary>
		Id,
		///<summary>Zip. </summary>
		Zip,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Licenses_Generator_DBFirst.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: dboAddress. </summary>
	public partial class dboAddressRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticdboAddressRelations
	{

		/// <summary>CTor</summary>
		static StaticdboAddressRelations() { }
	}
}
