//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Licenses_Generator_DBFirst.HelperClasses;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'dboAction'.<br/><br/></summary>
	[Serializable]
	public partial class dboActionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static dboActionEntityStaticMetaData _staticMetaData = new dboActionEntityStaticMetaData();
		private static dboActionRelations _relationsFactory = new dboActionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class dboActionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public dboActionEntityStaticMetaData()
			{
				SetEntityCoreInfo("dboActionEntity", InheritanceHierarchyType.None, false, (int)Licenses_Generator_DBFirst.EntityType.dboActionEntity, typeof(dboActionEntity), typeof(dboActionEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static dboActionEntity()
		{
		}

		/// <summary> CTor</summary>
		public dboActionEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public dboActionEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this dboActionEntity</param>
		public dboActionEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboAction which data should be fetched into this dboAction object</param>
		public dboActionEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboAction which data should be fetched into this dboAction object</param>
		/// <param name="validator">The custom validator object for this dboActionEntity</param>
		public dboActionEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected dboActionEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this dboActionEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static dboActionRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Comments property of the Entity dboAction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."comments".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Comments
		{
			get { return (System.String)GetValue((int)dboActionFieldIndex.Comments, true); }
			set	{ SetValue((int)dboActionFieldIndex.Comments, value); }
		}

		/// <summary>The Id property of the Entity dboAction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)dboActionFieldIndex.Id, true); }
			set { SetValue((int)dboActionFieldIndex.Id, value); }		}

		/// <summary>The RequestId property of the Entity dboAction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."RequestId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 RequestId
		{
			get { return (System.Int32)GetValue((int)dboActionFieldIndex.RequestId, true); }
			set	{ SetValue((int)dboActionFieldIndex.RequestId, value); }
		}

		/// <summary>The Type property of the Entity dboAction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."type".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Type
		{
			get { return (System.String)GetValue((int)dboActionFieldIndex.Type, true); }
			set	{ SetValue((int)dboActionFieldIndex.Type, value); }
		}

		/// <summary>The UserId property of the Entity dboAction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Actions"."UserId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UserId
		{
			get { return (System.Int32)GetValue((int)dboActionFieldIndex.UserId, true); }
			set	{ SetValue((int)dboActionFieldIndex.UserId, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Licenses_Generator_DBFirst
{
	public enum dboActionFieldIndex
	{
		///<summary>Comments. </summary>
		Comments,
		///<summary>Id. </summary>
		Id,
		///<summary>RequestId. </summary>
		RequestId,
		///<summary>Type. </summary>
		Type,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Licenses_Generator_DBFirst.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: dboAction. </summary>
	public partial class dboActionRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticdboActionRelations
	{

		/// <summary>CTor</summary>
		static StaticdboActionRelations() { }
	}
}
