//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Licenses_Generator_DBFirst.HelperClasses;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'dboLicenseRequest'.<br/><br/></summary>
	[Serializable]
	public partial class dboLicenseRequestEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static dboLicenseRequestEntityStaticMetaData _staticMetaData = new dboLicenseRequestEntityStaticMetaData();
		private static dboLicenseRequestRelations _relationsFactory = new dboLicenseRequestRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class dboLicenseRequestEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public dboLicenseRequestEntityStaticMetaData()
			{
				SetEntityCoreInfo("dboLicenseRequestEntity", InheritanceHierarchyType.None, false, (int)Licenses_Generator_DBFirst.EntityType.dboLicenseRequestEntity, typeof(dboLicenseRequestEntity), typeof(dboLicenseRequestEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static dboLicenseRequestEntity()
		{
		}

		/// <summary> CTor</summary>
		public dboLicenseRequestEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public dboLicenseRequestEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this dboLicenseRequestEntity</param>
		public dboLicenseRequestEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboLicenseRequest which data should be fetched into this dboLicenseRequest object</param>
		public dboLicenseRequestEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboLicenseRequest which data should be fetched into this dboLicenseRequest object</param>
		/// <param name="validator">The custom validator object for this dboLicenseRequestEntity</param>
		public dboLicenseRequestEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected dboLicenseRequestEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this dboLicenseRequestEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static dboLicenseRequestRelations Relations { get { return _relationsFactory; } }

		/// <summary>The ClientId property of the Entity dboLicenseRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License_Request"."ClientId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 ClientId
		{
			get { return (System.Int32)GetValue((int)dboLicenseRequestFieldIndex.ClientId, true); }
			set	{ SetValue((int)dboLicenseRequestFieldIndex.ClientId, value); }
		}

		/// <summary>The Id property of the Entity dboLicenseRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License_Request"."id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)dboLicenseRequestFieldIndex.Id, true); }
			set { SetValue((int)dboLicenseRequestFieldIndex.Id, value); }		}

		/// <summary>The IssuedTime property of the Entity dboLicenseRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License_Request"."issued-time".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime IssuedTime
		{
			get { return (System.DateTime)GetValue((int)dboLicenseRequestFieldIndex.IssuedTime, true); }
			set	{ SetValue((int)dboLicenseRequestFieldIndex.IssuedTime, value); }
		}

		/// <summary>The Status property of the Entity dboLicenseRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License_Request"."status".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Status
		{
			get { return (System.String)GetValue((int)dboLicenseRequestFieldIndex.Status, true); }
			set	{ SetValue((int)dboLicenseRequestFieldIndex.Status, value); }
		}

		/// <summary>The TypeId property of the Entity dboLicenseRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License_Request"."TypeId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 TypeId
		{
			get { return (System.Int32)GetValue((int)dboLicenseRequestFieldIndex.TypeId, true); }
			set	{ SetValue((int)dboLicenseRequestFieldIndex.TypeId, value); }
		}

		/// <summary>The UserId property of the Entity dboLicenseRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License_Request"."UserId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UserId
		{
			get { return (System.Int32)GetValue((int)dboLicenseRequestFieldIndex.UserId, true); }
			set	{ SetValue((int)dboLicenseRequestFieldIndex.UserId, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Licenses_Generator_DBFirst
{
	public enum dboLicenseRequestFieldIndex
	{
		///<summary>ClientId. </summary>
		ClientId,
		///<summary>Id. </summary>
		Id,
		///<summary>IssuedTime. </summary>
		IssuedTime,
		///<summary>Status. </summary>
		Status,
		///<summary>TypeId. </summary>
		TypeId,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Licenses_Generator_DBFirst.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: dboLicenseRequest. </summary>
	public partial class dboLicenseRequestRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticdboLicenseRequestRelations
	{

		/// <summary>CTor</summary>
		static StaticdboLicenseRequestRelations() { }
	}
}
