//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Licenses_Generator_DBFirst.HelperClasses;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'dboLicense'.<br/><br/></summary>
	[Serializable]
	public partial class dboLicenseEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static dboLicenseEntityStaticMetaData _staticMetaData = new dboLicenseEntityStaticMetaData();
		private static dboLicenseRelations _relationsFactory = new dboLicenseRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class dboLicenseEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public dboLicenseEntityStaticMetaData()
			{
				SetEntityCoreInfo("dboLicenseEntity", InheritanceHierarchyType.None, false, (int)Licenses_Generator_DBFirst.EntityType.dboLicenseEntity, typeof(dboLicenseEntity), typeof(dboLicenseEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static dboLicenseEntity()
		{
		}

		/// <summary> CTor</summary>
		public dboLicenseEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public dboLicenseEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this dboLicenseEntity</param>
		public dboLicenseEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboLicense which data should be fetched into this dboLicense object</param>
		public dboLicenseEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboLicense which data should be fetched into this dboLicense object</param>
		/// <param name="validator">The custom validator object for this dboLicenseEntity</param>
		public dboLicenseEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected dboLicenseEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this dboLicenseEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static dboLicenseRelations Relations { get { return _relationsFactory; } }

		/// <summary>The ClientId property of the Entity dboLicense<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License"."ClientId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 ClientId
		{
			get { return (System.Int32)GetValue((int)dboLicenseFieldIndex.ClientId, true); }
			set	{ SetValue((int)dboLicenseFieldIndex.ClientId, value); }
		}

		/// <summary>The Id property of the Entity dboLicense<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License"."id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)dboLicenseFieldIndex.Id, true); }
			set { SetValue((int)dboLicenseFieldIndex.Id, value); }		}

		/// <summary>The IssuedTime property of the Entity dboLicense<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License"."issued-time".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime IssuedTime
		{
			get { return (System.DateTime)GetValue((int)dboLicenseFieldIndex.IssuedTime, true); }
			set	{ SetValue((int)dboLicenseFieldIndex.IssuedTime, value); }
		}

		/// <summary>The RequestId property of the Entity dboLicense<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License"."RequestId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 RequestId
		{
			get { return (System.Int32)GetValue((int)dboLicenseFieldIndex.RequestId, true); }
			set	{ SetValue((int)dboLicenseFieldIndex.RequestId, value); }
		}

		/// <summary>The TypeId property of the Entity dboLicense<br/><br/></summary>
		/// <remarks>Mapped on  table field: "License"."TypeId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 TypeId
		{
			get { return (System.Int32)GetValue((int)dboLicenseFieldIndex.TypeId, true); }
			set	{ SetValue((int)dboLicenseFieldIndex.TypeId, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Licenses_Generator_DBFirst
{
	public enum dboLicenseFieldIndex
	{
		///<summary>ClientId. </summary>
		ClientId,
		///<summary>Id. </summary>
		Id,
		///<summary>IssuedTime. </summary>
		IssuedTime,
		///<summary>RequestId. </summary>
		RequestId,
		///<summary>TypeId. </summary>
		TypeId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Licenses_Generator_DBFirst.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: dboLicense. </summary>
	public partial class dboLicenseRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticdboLicenseRelations
	{

		/// <summary>CTor</summary>
		static StaticdboLicenseRelations() { }
	}
}
