//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Licenses_Generator_DBFirst.HelperClasses;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Document'.<br/><br/></summary>
	[Serializable]
	public partial class DocumentEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private ClientEntity _client;
		private LicenseRequestEntity _licenseRequest;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static DocumentEntityStaticMetaData _staticMetaData = new DocumentEntityStaticMetaData();
		private static DocumentRelations _relationsFactory = new DocumentRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Client</summary>
			public static readonly string Client = "Client";
			/// <summary>Member name LicenseRequest</summary>
			public static readonly string LicenseRequest = "LicenseRequest";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DocumentEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DocumentEntityStaticMetaData()
			{
				SetEntityCoreInfo("DocumentEntity", InheritanceHierarchyType.None, false, (int)Licenses_Generator_DBFirst.EntityType.DocumentEntity, typeof(DocumentEntity), typeof(DocumentEntityFactory), false);
				AddNavigatorMetaData<DocumentEntity, ClientEntity>("Client", "Documents", (a, b) => a._client = b, a => a._client, (a, b) => a.Client = b, Licenses_Generator_DBFirst.RelationClasses.StaticDocumentRelations.ClientEntityUsingClientIdStatic, ()=>new DocumentRelations().ClientEntityUsingClientId, null, new int[] { (int)DocumentFieldIndex.ClientId }, null, true, (int)Licenses_Generator_DBFirst.EntityType.ClientEntity);
				AddNavigatorMetaData<DocumentEntity, LicenseRequestEntity>("LicenseRequest", "Documents", (a, b) => a._licenseRequest = b, a => a._licenseRequest, (a, b) => a.LicenseRequest = b, Licenses_Generator_DBFirst.RelationClasses.StaticDocumentRelations.LicenseRequestEntityUsingRequestIdStatic, ()=>new DocumentRelations().LicenseRequestEntityUsingRequestId, null, new int[] { (int)DocumentFieldIndex.RequestId }, null, true, (int)Licenses_Generator_DBFirst.EntityType.LicenseRequestEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static DocumentEntity()
		{
		}

		/// <summary> CTor</summary>
		public DocumentEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DocumentEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DocumentEntity</param>
		public DocumentEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Document which data should be fetched into this Document object</param>
		public DocumentEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Document which data should be fetched into this Document object</param>
		/// <param name="validator">The custom validator object for this DocumentEntity</param>
		public DocumentEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DocumentEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Client' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoClient() { return CreateRelationInfoForNavigator("Client"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'LicenseRequest' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoLicenseRequest() { return CreateRelationInfoForNavigator("LicenseRequest"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DocumentEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DocumentRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Client' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathClient { get { return _staticMetaData.GetPrefetchPathElement("Client", CommonEntityBase.CreateEntityCollection<ClientEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'LicenseRequest' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathLicenseRequest { get { return _staticMetaData.GetPrefetchPathElement("LicenseRequest", CommonEntityBase.CreateEntityCollection<LicenseRequestEntity>()); } }

		/// <summary>The ClientId property of the Entity Document<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Documents"."ClientId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 ClientId
		{
			get { return (System.Int32)GetValue((int)DocumentFieldIndex.ClientId, true); }
			set	{ SetValue((int)DocumentFieldIndex.ClientId, value); }
		}

		/// <summary>The Comments property of the Entity Document<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Documents"."comments".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Comments
		{
			get { return (System.String)GetValue((int)DocumentFieldIndex.Comments, true); }
			set	{ SetValue((int)DocumentFieldIndex.Comments, value); }
		}

		/// <summary>The Id property of the Entity Document<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Documents"."id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)DocumentFieldIndex.Id, true); }
			set { SetValue((int)DocumentFieldIndex.Id, value); }		}

		/// <summary>The Link property of the Entity Document<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Documents"."link".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Link
		{
			get { return (System.String)GetValue((int)DocumentFieldIndex.Link, true); }
			set	{ SetValue((int)DocumentFieldIndex.Link, value); }
		}

		/// <summary>The RequestId property of the Entity Document<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Documents"."RequestId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 RequestId
		{
			get { return (System.Int32)GetValue((int)DocumentFieldIndex.RequestId, true); }
			set	{ SetValue((int)DocumentFieldIndex.RequestId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ClientEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ClientEntity Client
		{
			get { return _client; }
			set { SetSingleRelatedEntityNavigator(value, "Client"); }
		}

		/// <summary>Gets / sets related entity of type 'LicenseRequestEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual LicenseRequestEntity LicenseRequest
		{
			get { return _licenseRequest; }
			set { SetSingleRelatedEntityNavigator(value, "LicenseRequest"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Licenses_Generator_DBFirst
{
	public enum DocumentFieldIndex
	{
		///<summary>ClientId. </summary>
		ClientId,
		///<summary>Comments. </summary>
		Comments,
		///<summary>Id. </summary>
		Id,
		///<summary>Link. </summary>
		Link,
		///<summary>RequestId. </summary>
		RequestId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Licenses_Generator_DBFirst.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Document. </summary>
	public partial class DocumentRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between DocumentEntity and ClientEntity over the m:1 relation they have, using the relation between the fields: Document.ClientId - Client.Id</summary>
		public virtual IEntityRelation ClientEntityUsingClientId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Client", false, new[] { ClientFields.Id, DocumentFields.ClientId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DocumentEntity and LicenseRequestEntity over the m:1 relation they have, using the relation between the fields: Document.RequestId - LicenseRequest.Id</summary>
		public virtual IEntityRelation LicenseRequestEntityUsingRequestId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "LicenseRequest", false, new[] { LicenseRequestFields.Id, DocumentFields.RequestId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDocumentRelations
	{
		internal static readonly IEntityRelation ClientEntityUsingClientIdStatic = new DocumentRelations().ClientEntityUsingClientId;
		internal static readonly IEntityRelation LicenseRequestEntityUsingRequestIdStatic = new DocumentRelations().LicenseRequestEntityUsingRequestId;

		/// <summary>CTor</summary>
		static StaticDocumentRelations() { }
	}
}
