//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Licenses_Generator_DBFirst.HelperClasses;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'VersionInfo'.<br/><br/></summary>
	[Serializable]
	public partial class VersionInfoEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static VersionInfoEntityStaticMetaData _staticMetaData = new VersionInfoEntityStaticMetaData();
		private static VersionInfoRelations _relationsFactory = new VersionInfoRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class VersionInfoEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public VersionInfoEntityStaticMetaData()
			{
				SetEntityCoreInfo("VersionInfoEntity", InheritanceHierarchyType.None, false, (int)Licenses_Generator_DBFirst.EntityType.VersionInfoEntity, typeof(VersionInfoEntity), typeof(VersionInfoEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static VersionInfoEntity()
		{
		}

		/// <summary> CTor</summary>
		public VersionInfoEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public VersionInfoEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this VersionInfoEntity</param>
		public VersionInfoEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected VersionInfoEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this VersionInfoEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static VersionInfoRelations Relations { get { return _relationsFactory; } }

		/// <summary>The AppliedOn property of the Entity VersionInfo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "VersionInfo"."AppliedOn".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppliedOn
		{
			get { return (Nullable<System.DateTime>)GetValue((int)VersionInfoFieldIndex.AppliedOn, false); }
			set	{ SetValue((int)VersionInfoFieldIndex.AppliedOn, value); }
		}

		/// <summary>The Description property of the Entity VersionInfo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "VersionInfo"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 1024.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)VersionInfoFieldIndex.Description, true); }
			set	{ SetValue((int)VersionInfoFieldIndex.Description, value); }
		}

		/// <summary>The Version property of the Entity VersionInfo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "VersionInfo"."Version".<br/>Table field type characteristics (type, precision, scale, length): BigInt, 19, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int64 Version
		{
			get { return (System.Int64)GetValue((int)VersionInfoFieldIndex.Version, true); }
			set	{ SetValue((int)VersionInfoFieldIndex.Version, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Licenses_Generator_DBFirst
{
	public enum VersionInfoFieldIndex
	{
		///<summary>AppliedOn. </summary>
		AppliedOn,
		///<summary>Description. </summary>
		Description,
		///<summary>Version. </summary>
		Version,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Licenses_Generator_DBFirst.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: VersionInfo. </summary>
	public partial class VersionInfoRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticVersionInfoRelations
	{

		/// <summary>CTor</summary>
		static StaticVersionInfoRelations() { }
	}
}
