//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.HelperClasses
{
	/// <summary>Field Creation Class for entity ActionEntity</summary>
	public partial class ActionFields
	{
		/// <summary>Creates a new ActionEntity.Comments field instance</summary>
		public static EntityField2 Comments { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ActionFieldIndex.Comments); }}
		/// <summary>Creates a new ActionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ActionFieldIndex.Id); }}
		/// <summary>Creates a new ActionEntity.RequestId field instance</summary>
		public static EntityField2 RequestId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ActionFieldIndex.RequestId); }}
		/// <summary>Creates a new ActionEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ActionFieldIndex.Type); }}
		/// <summary>Creates a new ActionEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ActionFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity AddressEntity</summary>
	public partial class AddressFields
	{
		/// <summary>Creates a new AddressEntity.Address field instance</summary>
		public static EntityField2 Address { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Address); }}
		/// <summary>Creates a new AddressEntity.City field instance</summary>
		public static EntityField2 City { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.City); }}
		/// <summary>Creates a new AddressEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.ClientId); }}
		/// <summary>Creates a new AddressEntity.Governorate field instance</summary>
		public static EntityField2 Governorate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Governorate); }}
		/// <summary>Creates a new AddressEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Id); }}
		/// <summary>Creates a new AddressEntity.Zip field instance</summary>
		public static EntityField2 Zip { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Zip); }}
	}

	/// <summary>Field Creation Class for entity CityEntity</summary>
	public partial class CityFields
	{
		/// <summary>Creates a new CityEntity.GovernorateId field instance</summary>
		public static EntityField2 GovernorateId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CityFieldIndex.GovernorateId); }}
		/// <summary>Creates a new CityEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CityFieldIndex.Id); }}
		/// <summary>Creates a new CityEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CityFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity ClientEntity</summary>
	public partial class ClientFields
	{
		/// <summary>Creates a new ClientEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ClientFieldIndex.Id); }}
		/// <summary>Creates a new ClientEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ClientFieldIndex.Name); }}
		/// <summary>Creates a new ClientEntity.NationalId field instance</summary>
		public static EntityField2 NationalId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ClientFieldIndex.NationalId); }}
	}

	/// <summary>Field Creation Class for entity dboActionEntity</summary>
	public partial class dboActionFields
	{
		/// <summary>Creates a new dboActionEntity.Comments field instance</summary>
		public static EntityField2 Comments { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboActionFieldIndex.Comments); }}
		/// <summary>Creates a new dboActionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboActionFieldIndex.Id); }}
		/// <summary>Creates a new dboActionEntity.RequestId field instance</summary>
		public static EntityField2 RequestId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboActionFieldIndex.RequestId); }}
		/// <summary>Creates a new dboActionEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboActionFieldIndex.Type); }}
		/// <summary>Creates a new dboActionEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboActionFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity dboAddressEntity</summary>
	public partial class dboAddressFields
	{
		/// <summary>Creates a new dboAddressEntity.Address field instance</summary>
		public static EntityField2 Address { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboAddressFieldIndex.Address); }}
		/// <summary>Creates a new dboAddressEntity.City field instance</summary>
		public static EntityField2 City { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboAddressFieldIndex.City); }}
		/// <summary>Creates a new dboAddressEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboAddressFieldIndex.ClientId); }}
		/// <summary>Creates a new dboAddressEntity.Governorate field instance</summary>
		public static EntityField2 Governorate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboAddressFieldIndex.Governorate); }}
		/// <summary>Creates a new dboAddressEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboAddressFieldIndex.Id); }}
		/// <summary>Creates a new dboAddressEntity.Zip field instance</summary>
		public static EntityField2 Zip { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboAddressFieldIndex.Zip); }}
	}

	/// <summary>Field Creation Class for entity dboCityEntity</summary>
	public partial class dboCityFields
	{
		/// <summary>Creates a new dboCityEntity.GovernorateId field instance</summary>
		public static EntityField2 GovernorateId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboCityFieldIndex.GovernorateId); }}
		/// <summary>Creates a new dboCityEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboCityFieldIndex.Id); }}
		/// <summary>Creates a new dboCityEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboCityFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity dboClientEntity</summary>
	public partial class dboClientFields
	{
		/// <summary>Creates a new dboClientEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboClientFieldIndex.Id); }}
		/// <summary>Creates a new dboClientEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboClientFieldIndex.Name); }}
		/// <summary>Creates a new dboClientEntity.NationalId field instance</summary>
		public static EntityField2 NationalId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboClientFieldIndex.NationalId); }}
	}

	/// <summary>Field Creation Class for entity dboDocumentEntity</summary>
	public partial class dboDocumentFields
	{
		/// <summary>Creates a new dboDocumentEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboDocumentFieldIndex.ClientId); }}
		/// <summary>Creates a new dboDocumentEntity.Comments field instance</summary>
		public static EntityField2 Comments { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboDocumentFieldIndex.Comments); }}
		/// <summary>Creates a new dboDocumentEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboDocumentFieldIndex.Id); }}
		/// <summary>Creates a new dboDocumentEntity.Link field instance</summary>
		public static EntityField2 Link { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboDocumentFieldIndex.Link); }}
		/// <summary>Creates a new dboDocumentEntity.RequestId field instance</summary>
		public static EntityField2 RequestId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboDocumentFieldIndex.RequestId); }}
	}

	/// <summary>Field Creation Class for entity dboGovernorateEntity</summary>
	public partial class dboGovernorateFields
	{
		/// <summary>Creates a new dboGovernorateEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboGovernorateFieldIndex.Id); }}
		/// <summary>Creates a new dboGovernorateEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboGovernorateFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity dboLicenseEntity</summary>
	public partial class dboLicenseFields
	{
		/// <summary>Creates a new dboLicenseEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseFieldIndex.ClientId); }}
		/// <summary>Creates a new dboLicenseEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseFieldIndex.Id); }}
		/// <summary>Creates a new dboLicenseEntity.IssuedTime field instance</summary>
		public static EntityField2 IssuedTime { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseFieldIndex.IssuedTime); }}
		/// <summary>Creates a new dboLicenseEntity.RequestId field instance</summary>
		public static EntityField2 RequestId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseFieldIndex.RequestId); }}
		/// <summary>Creates a new dboLicenseEntity.TypeId field instance</summary>
		public static EntityField2 TypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseFieldIndex.TypeId); }}
	}

	/// <summary>Field Creation Class for entity dboLicenseRequestEntity</summary>
	public partial class dboLicenseRequestFields
	{
		/// <summary>Creates a new dboLicenseRequestEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseRequestFieldIndex.ClientId); }}
		/// <summary>Creates a new dboLicenseRequestEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseRequestFieldIndex.Id); }}
		/// <summary>Creates a new dboLicenseRequestEntity.IssuedTime field instance</summary>
		public static EntityField2 IssuedTime { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseRequestFieldIndex.IssuedTime); }}
		/// <summary>Creates a new dboLicenseRequestEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseRequestFieldIndex.Status); }}
		/// <summary>Creates a new dboLicenseRequestEntity.TypeId field instance</summary>
		public static EntityField2 TypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseRequestFieldIndex.TypeId); }}
		/// <summary>Creates a new dboLicenseRequestEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseRequestFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity dboLicenseTypeEntity</summary>
	public partial class dboLicenseTypeFields
	{
		/// <summary>Creates a new dboLicenseTypeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseTypeFieldIndex.Id); }}
		/// <summary>Creates a new dboLicenseTypeEntity.TimeTillExpire field instance</summary>
		public static EntityField2 TimeTillExpire { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseTypeFieldIndex.TimeTillExpire); }}
		/// <summary>Creates a new dboLicenseTypeEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboLicenseTypeFieldIndex.Type); }}
	}

	/// <summary>Field Creation Class for entity dboUserEntity</summary>
	public partial class dboUserFields
	{
		/// <summary>Creates a new dboUserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboUserFieldIndex.Id); }}
		/// <summary>Creates a new dboUserEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboUserFieldIndex.Name); }}
		/// <summary>Creates a new dboUserEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboUserFieldIndex.Password); }}
		/// <summary>Creates a new dboUserEntity.Role field instance</summary>
		public static EntityField2 Role { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboUserFieldIndex.Role); }}
		/// <summary>Creates a new dboUserEntity.Username field instance</summary>
		public static EntityField2 Username { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboUserFieldIndex.Username); }}
	}

	/// <summary>Field Creation Class for entity dboVersionInfoEntity</summary>
	public partial class dboVersionInfoFields
	{
		/// <summary>Creates a new dboVersionInfoEntity.AppliedOn field instance</summary>
		public static EntityField2 AppliedOn { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboVersionInfoFieldIndex.AppliedOn); }}
		/// <summary>Creates a new dboVersionInfoEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboVersionInfoFieldIndex.Description); }}
		/// <summary>Creates a new dboVersionInfoEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboVersionInfoFieldIndex.Version); }}
	}

	/// <summary>Field Creation Class for entity DocumentEntity</summary>
	public partial class DocumentFields
	{
		/// <summary>Creates a new DocumentEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.ClientId); }}
		/// <summary>Creates a new DocumentEntity.Comments field instance</summary>
		public static EntityField2 Comments { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.Comments); }}
		/// <summary>Creates a new DocumentEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.Id); }}
		/// <summary>Creates a new DocumentEntity.Link field instance</summary>
		public static EntityField2 Link { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.Link); }}
		/// <summary>Creates a new DocumentEntity.RequestId field instance</summary>
		public static EntityField2 RequestId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.RequestId); }}
	}

	/// <summary>Field Creation Class for entity GovernorateEntity</summary>
	public partial class GovernorateFields
	{
		/// <summary>Creates a new GovernorateEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(GovernorateFieldIndex.Id); }}
		/// <summary>Creates a new GovernorateEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(GovernorateFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity LicenseEntity</summary>
	public partial class LicenseFields
	{
		/// <summary>Creates a new LicenseEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseFieldIndex.ClientId); }}
		/// <summary>Creates a new LicenseEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseFieldIndex.Id); }}
		/// <summary>Creates a new LicenseEntity.IssuedTime field instance</summary>
		public static EntityField2 IssuedTime { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseFieldIndex.IssuedTime); }}
		/// <summary>Creates a new LicenseEntity.RequestId field instance</summary>
		public static EntityField2 RequestId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseFieldIndex.RequestId); }}
		/// <summary>Creates a new LicenseEntity.TypeId field instance</summary>
		public static EntityField2 TypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseFieldIndex.TypeId); }}
	}

	/// <summary>Field Creation Class for entity LicenseRequestEntity</summary>
	public partial class LicenseRequestFields
	{
		/// <summary>Creates a new LicenseRequestEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseRequestFieldIndex.ClientId); }}
		/// <summary>Creates a new LicenseRequestEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseRequestFieldIndex.Id); }}
		/// <summary>Creates a new LicenseRequestEntity.IssuedTime field instance</summary>
		public static EntityField2 IssuedTime { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseRequestFieldIndex.IssuedTime); }}
		/// <summary>Creates a new LicenseRequestEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseRequestFieldIndex.Status); }}
		/// <summary>Creates a new LicenseRequestEntity.TypeId field instance</summary>
		public static EntityField2 TypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseRequestFieldIndex.TypeId); }}
		/// <summary>Creates a new LicenseRequestEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseRequestFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity LicenseTypeEntity</summary>
	public partial class LicenseTypeFields
	{
		/// <summary>Creates a new LicenseTypeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseTypeFieldIndex.Id); }}
		/// <summary>Creates a new LicenseTypeEntity.TimeTillExpire field instance</summary>
		public static EntityField2 TimeTillExpire { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseTypeFieldIndex.TimeTillExpire); }}
		/// <summary>Creates a new LicenseTypeEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LicenseTypeFieldIndex.Type); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Name); }}
		/// <summary>Creates a new UserEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Password); }}
		/// <summary>Creates a new UserEntity.Role field instance</summary>
		public static EntityField2 Role { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Role); }}
		/// <summary>Creates a new UserEntity.Username field instance</summary>
		public static EntityField2 Username { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Username); }}
	}

	/// <summary>Field Creation Class for entity VersionInfoEntity</summary>
	public partial class VersionInfoFields
	{
		/// <summary>Creates a new VersionInfoEntity.AppliedOn field instance</summary>
		public static EntityField2 AppliedOn { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VersionInfoFieldIndex.AppliedOn); }}
		/// <summary>Creates a new VersionInfoEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VersionInfoFieldIndex.Description); }}
		/// <summary>Creates a new VersionInfoEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VersionInfoFieldIndex.Version); }}
	}
	

}