//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Licenses_Generator_DBFirst.FactoryClasses;
using Licenses_Generator_DBFirst.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitActionEntityInfo();
			InitAddressEntityInfo();
			InitCityEntityInfo();
			InitClientEntityInfo();
			InitdboActionEntityInfo();
			InitdboAddressEntityInfo();
			InitdboCityEntityInfo();
			InitdboClientEntityInfo();
			InitdboDocumentEntityInfo();
			InitdboGovernorateEntityInfo();
			InitdboLicenseEntityInfo();
			InitdboLicenseRequestEntityInfo();
			InitdboLicenseTypeEntityInfo();
			InitdboUserEntityInfo();
			InitdboVersionInfoEntityInfo();
			InitDocumentEntityInfo();
			InitGovernorateEntityInfo();
			InitLicenseEntityInfo();
			InitLicenseRequestEntityInfo();
			InitLicenseTypeEntityInfo();
			InitUserEntityInfo();
			InitVersionInfoEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits ActionEntity's info objects</summary>
		private void InitActionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ActionFieldIndex), "ActionEntity");
			this.AddElementFieldInfo("ActionEntity", "Comments", typeof(System.String), false, false, false, false,  (int)ActionFieldIndex.Comments, 255, 0, 0);
			this.AddElementFieldInfo("ActionEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)ActionFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("ActionEntity", "RequestId", typeof(System.Int32), false, true, false, false,  (int)ActionFieldIndex.RequestId, 0, 0, 10);
			this.AddElementFieldInfo("ActionEntity", "Type", typeof(System.String), false, false, false, false,  (int)ActionFieldIndex.Type, 255, 0, 0);
			this.AddElementFieldInfo("ActionEntity", "UserId", typeof(System.Int32), false, true, false, false,  (int)ActionFieldIndex.UserId, 0, 0, 10);
		}

		/// <summary>Inits AddressEntity's info objects</summary>
		private void InitAddressEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(AddressFieldIndex), "AddressEntity");
			this.AddElementFieldInfo("AddressEntity", "Address", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.Address, 255, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "City", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.City, 255, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "ClientId", typeof(System.Int32), false, true, false, false,  (int)AddressFieldIndex.ClientId, 0, 0, 10);
			this.AddElementFieldInfo("AddressEntity", "Governorate", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.Governorate, 255, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)AddressFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("AddressEntity", "Zip", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.Zip, 255, 0, 0);
		}

		/// <summary>Inits CityEntity's info objects</summary>
		private void InitCityEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CityFieldIndex), "CityEntity");
			this.AddElementFieldInfo("CityEntity", "GovernorateId", typeof(System.Int32), false, true, false, false,  (int)CityFieldIndex.GovernorateId, 0, 0, 10);
			this.AddElementFieldInfo("CityEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)CityFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("CityEntity", "Name", typeof(System.String), false, false, false, false,  (int)CityFieldIndex.Name, 255, 0, 0);
		}

		/// <summary>Inits ClientEntity's info objects</summary>
		private void InitClientEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ClientFieldIndex), "ClientEntity");
			this.AddElementFieldInfo("ClientEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)ClientFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("ClientEntity", "Name", typeof(System.String), false, false, false, false,  (int)ClientFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("ClientEntity", "NationalId", typeof(System.String), false, false, false, false,  (int)ClientFieldIndex.NationalId, 255, 0, 0);
		}

		/// <summary>Inits dboActionEntity's info objects</summary>
		private void InitdboActionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboActionFieldIndex), "dboActionEntity");
			this.AddElementFieldInfo("dboActionEntity", "Comments", typeof(System.String), false, false, false, false,  (int)dboActionFieldIndex.Comments, 255, 0, 0);
			this.AddElementFieldInfo("dboActionEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboActionFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboActionEntity", "RequestId", typeof(System.Int32), false, false, false, false,  (int)dboActionFieldIndex.RequestId, 0, 0, 10);
			this.AddElementFieldInfo("dboActionEntity", "Type", typeof(System.String), false, false, false, false,  (int)dboActionFieldIndex.Type, 255, 0, 0);
			this.AddElementFieldInfo("dboActionEntity", "UserId", typeof(System.Int32), false, false, false, false,  (int)dboActionFieldIndex.UserId, 0, 0, 10);
		}

		/// <summary>Inits dboAddressEntity's info objects</summary>
		private void InitdboAddressEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboAddressFieldIndex), "dboAddressEntity");
			this.AddElementFieldInfo("dboAddressEntity", "Address", typeof(System.String), false, false, false, false,  (int)dboAddressFieldIndex.Address, 255, 0, 0);
			this.AddElementFieldInfo("dboAddressEntity", "City", typeof(System.String), false, false, false, false,  (int)dboAddressFieldIndex.City, 255, 0, 0);
			this.AddElementFieldInfo("dboAddressEntity", "ClientId", typeof(System.Int32), false, false, false, false,  (int)dboAddressFieldIndex.ClientId, 0, 0, 10);
			this.AddElementFieldInfo("dboAddressEntity", "Governorate", typeof(System.String), false, false, false, false,  (int)dboAddressFieldIndex.Governorate, 255, 0, 0);
			this.AddElementFieldInfo("dboAddressEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboAddressFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboAddressEntity", "Zip", typeof(System.String), false, false, false, false,  (int)dboAddressFieldIndex.Zip, 255, 0, 0);
		}

		/// <summary>Inits dboCityEntity's info objects</summary>
		private void InitdboCityEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboCityFieldIndex), "dboCityEntity");
			this.AddElementFieldInfo("dboCityEntity", "GovernorateId", typeof(System.Int32), false, false, false, false,  (int)dboCityFieldIndex.GovernorateId, 0, 0, 10);
			this.AddElementFieldInfo("dboCityEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboCityFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboCityEntity", "Name", typeof(System.String), false, false, false, false,  (int)dboCityFieldIndex.Name, 255, 0, 0);
		}

		/// <summary>Inits dboClientEntity's info objects</summary>
		private void InitdboClientEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboClientFieldIndex), "dboClientEntity");
			this.AddElementFieldInfo("dboClientEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboClientFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboClientEntity", "Name", typeof(System.String), false, false, false, false,  (int)dboClientFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("dboClientEntity", "NationalId", typeof(System.String), false, false, false, false,  (int)dboClientFieldIndex.NationalId, 255, 0, 0);
		}

		/// <summary>Inits dboDocumentEntity's info objects</summary>
		private void InitdboDocumentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboDocumentFieldIndex), "dboDocumentEntity");
			this.AddElementFieldInfo("dboDocumentEntity", "ClientId", typeof(System.Int32), false, false, false, false,  (int)dboDocumentFieldIndex.ClientId, 0, 0, 10);
			this.AddElementFieldInfo("dboDocumentEntity", "Comments", typeof(System.String), false, false, false, false,  (int)dboDocumentFieldIndex.Comments, 255, 0, 0);
			this.AddElementFieldInfo("dboDocumentEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboDocumentFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboDocumentEntity", "Link", typeof(System.String), false, false, false, false,  (int)dboDocumentFieldIndex.Link, 255, 0, 0);
			this.AddElementFieldInfo("dboDocumentEntity", "RequestId", typeof(System.Int32), false, false, false, false,  (int)dboDocumentFieldIndex.RequestId, 0, 0, 10);
		}

		/// <summary>Inits dboGovernorateEntity's info objects</summary>
		private void InitdboGovernorateEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboGovernorateFieldIndex), "dboGovernorateEntity");
			this.AddElementFieldInfo("dboGovernorateEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboGovernorateFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboGovernorateEntity", "Name", typeof(System.String), false, false, false, false,  (int)dboGovernorateFieldIndex.Name, 255, 0, 0);
		}

		/// <summary>Inits dboLicenseEntity's info objects</summary>
		private void InitdboLicenseEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboLicenseFieldIndex), "dboLicenseEntity");
			this.AddElementFieldInfo("dboLicenseEntity", "ClientId", typeof(System.Int32), false, false, false, false,  (int)dboLicenseFieldIndex.ClientId, 0, 0, 10);
			this.AddElementFieldInfo("dboLicenseEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboLicenseFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboLicenseEntity", "IssuedTime", typeof(System.DateTime), false, false, false, false,  (int)dboLicenseFieldIndex.IssuedTime, 0, 0, 0);
			this.AddElementFieldInfo("dboLicenseEntity", "RequestId", typeof(System.Int32), false, false, false, false,  (int)dboLicenseFieldIndex.RequestId, 0, 0, 10);
			this.AddElementFieldInfo("dboLicenseEntity", "TypeId", typeof(System.Int32), false, false, false, false,  (int)dboLicenseFieldIndex.TypeId, 0, 0, 10);
		}

		/// <summary>Inits dboLicenseRequestEntity's info objects</summary>
		private void InitdboLicenseRequestEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboLicenseRequestFieldIndex), "dboLicenseRequestEntity");
			this.AddElementFieldInfo("dboLicenseRequestEntity", "ClientId", typeof(System.Int32), false, false, false, false,  (int)dboLicenseRequestFieldIndex.ClientId, 0, 0, 10);
			this.AddElementFieldInfo("dboLicenseRequestEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboLicenseRequestFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboLicenseRequestEntity", "IssuedTime", typeof(System.DateTime), false, false, false, false,  (int)dboLicenseRequestFieldIndex.IssuedTime, 0, 0, 0);
			this.AddElementFieldInfo("dboLicenseRequestEntity", "Status", typeof(System.String), false, false, false, false,  (int)dboLicenseRequestFieldIndex.Status, 255, 0, 0);
			this.AddElementFieldInfo("dboLicenseRequestEntity", "TypeId", typeof(System.Int32), false, false, false, false,  (int)dboLicenseRequestFieldIndex.TypeId, 0, 0, 10);
			this.AddElementFieldInfo("dboLicenseRequestEntity", "UserId", typeof(System.Int32), false, false, false, false,  (int)dboLicenseRequestFieldIndex.UserId, 0, 0, 10);
		}

		/// <summary>Inits dboLicenseTypeEntity's info objects</summary>
		private void InitdboLicenseTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboLicenseTypeFieldIndex), "dboLicenseTypeEntity");
			this.AddElementFieldInfo("dboLicenseTypeEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboLicenseTypeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboLicenseTypeEntity", "TimeTillExpire", typeof(System.String), false, false, false, false,  (int)dboLicenseTypeFieldIndex.TimeTillExpire, 255, 0, 0);
			this.AddElementFieldInfo("dboLicenseTypeEntity", "Type", typeof(System.String), false, false, false, false,  (int)dboLicenseTypeFieldIndex.Type, 255, 0, 0);
		}

		/// <summary>Inits dboUserEntity's info objects</summary>
		private void InitdboUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboUserFieldIndex), "dboUserEntity");
			this.AddElementFieldInfo("dboUserEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboUserFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboUserEntity", "Name", typeof(System.String), false, false, false, false,  (int)dboUserFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("dboUserEntity", "Password", typeof(System.String), false, false, false, false,  (int)dboUserFieldIndex.Password, 255, 0, 0);
			this.AddElementFieldInfo("dboUserEntity", "Role", typeof(System.String), false, false, false, false,  (int)dboUserFieldIndex.Role, 255, 0, 0);
			this.AddElementFieldInfo("dboUserEntity", "Username", typeof(System.String), false, false, false, false,  (int)dboUserFieldIndex.Username, 255, 0, 0);
		}

		/// <summary>Inits dboVersionInfoEntity's info objects</summary>
		private void InitdboVersionInfoEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboVersionInfoFieldIndex), "dboVersionInfoEntity");
			this.AddElementFieldInfo("dboVersionInfoEntity", "AppliedOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)dboVersionInfoFieldIndex.AppliedOn, 0, 0, 0);
			this.AddElementFieldInfo("dboVersionInfoEntity", "Description", typeof(System.String), false, false, false, true,  (int)dboVersionInfoFieldIndex.Description, 1024, 0, 0);
			this.AddElementFieldInfo("dboVersionInfoEntity", "Version", typeof(System.Int64), false, false, false, false,  (int)dboVersionInfoFieldIndex.Version, 0, 0, 19);
		}

		/// <summary>Inits DocumentEntity's info objects</summary>
		private void InitDocumentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(DocumentFieldIndex), "DocumentEntity");
			this.AddElementFieldInfo("DocumentEntity", "ClientId", typeof(System.Int32), false, true, false, false,  (int)DocumentFieldIndex.ClientId, 0, 0, 10);
			this.AddElementFieldInfo("DocumentEntity", "Comments", typeof(System.String), false, false, false, false,  (int)DocumentFieldIndex.Comments, 255, 0, 0);
			this.AddElementFieldInfo("DocumentEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)DocumentFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("DocumentEntity", "Link", typeof(System.String), false, false, false, false,  (int)DocumentFieldIndex.Link, 255, 0, 0);
			this.AddElementFieldInfo("DocumentEntity", "RequestId", typeof(System.Int32), false, true, false, false,  (int)DocumentFieldIndex.RequestId, 0, 0, 10);
		}

		/// <summary>Inits GovernorateEntity's info objects</summary>
		private void InitGovernorateEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(GovernorateFieldIndex), "GovernorateEntity");
			this.AddElementFieldInfo("GovernorateEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)GovernorateFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("GovernorateEntity", "Name", typeof(System.String), false, false, false, false,  (int)GovernorateFieldIndex.Name, 255, 0, 0);
		}

		/// <summary>Inits LicenseEntity's info objects</summary>
		private void InitLicenseEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(LicenseFieldIndex), "LicenseEntity");
			this.AddElementFieldInfo("LicenseEntity", "ClientId", typeof(System.Int32), false, true, false, false,  (int)LicenseFieldIndex.ClientId, 0, 0, 10);
			this.AddElementFieldInfo("LicenseEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)LicenseFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("LicenseEntity", "IssuedTime", typeof(System.DateTime), false, false, false, false,  (int)LicenseFieldIndex.IssuedTime, 0, 0, 0);
			this.AddElementFieldInfo("LicenseEntity", "RequestId", typeof(System.Int32), false, true, false, false,  (int)LicenseFieldIndex.RequestId, 0, 0, 10);
			this.AddElementFieldInfo("LicenseEntity", "TypeId", typeof(System.Int32), false, true, false, false,  (int)LicenseFieldIndex.TypeId, 0, 0, 10);
		}

		/// <summary>Inits LicenseRequestEntity's info objects</summary>
		private void InitLicenseRequestEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(LicenseRequestFieldIndex), "LicenseRequestEntity");
			this.AddElementFieldInfo("LicenseRequestEntity", "ClientId", typeof(System.Int32), false, true, false, false,  (int)LicenseRequestFieldIndex.ClientId, 0, 0, 10);
			this.AddElementFieldInfo("LicenseRequestEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)LicenseRequestFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("LicenseRequestEntity", "IssuedTime", typeof(System.DateTime), false, false, false, false,  (int)LicenseRequestFieldIndex.IssuedTime, 0, 0, 0);
			this.AddElementFieldInfo("LicenseRequestEntity", "Status", typeof(System.String), false, false, false, false,  (int)LicenseRequestFieldIndex.Status, 255, 0, 0);
			this.AddElementFieldInfo("LicenseRequestEntity", "TypeId", typeof(System.Int32), false, true, false, false,  (int)LicenseRequestFieldIndex.TypeId, 0, 0, 10);
			this.AddElementFieldInfo("LicenseRequestEntity", "UserId", typeof(System.Int32), false, true, false, false,  (int)LicenseRequestFieldIndex.UserId, 0, 0, 10);
		}

		/// <summary>Inits LicenseTypeEntity's info objects</summary>
		private void InitLicenseTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(LicenseTypeFieldIndex), "LicenseTypeEntity");
			this.AddElementFieldInfo("LicenseTypeEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)LicenseTypeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("LicenseTypeEntity", "TimeTillExpire", typeof(System.String), false, false, false, false,  (int)LicenseTypeFieldIndex.TimeTillExpire, 255, 0, 0);
			this.AddElementFieldInfo("LicenseTypeEntity", "Type", typeof(System.String), false, false, false, false,  (int)LicenseTypeFieldIndex.Type, 255, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)UserFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "Name", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Password", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Password, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Role", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Role, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Username", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Username, 255, 0, 0);
		}

		/// <summary>Inits VersionInfoEntity's info objects</summary>
		private void InitVersionInfoEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(VersionInfoFieldIndex), "VersionInfoEntity");
			this.AddElementFieldInfo("VersionInfoEntity", "AppliedOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)VersionInfoFieldIndex.AppliedOn, 0, 0, 0);
			this.AddElementFieldInfo("VersionInfoEntity", "Description", typeof(System.String), false, false, false, true,  (int)VersionInfoFieldIndex.Description, 1024, 0, 0);
			this.AddElementFieldInfo("VersionInfoEntity", "Version", typeof(System.Int64), false, false, false, false,  (int)VersionInfoFieldIndex.Version, 0, 0, 19);
		}
	}
}