//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Licenses_Generator_DBFirst.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitActionEntityMappings();
			InitAddressEntityMappings();
			InitCityEntityMappings();
			InitClientEntityMappings();
			InitdboActionEntityMappings();
			InitdboAddressEntityMappings();
			InitdboCityEntityMappings();
			InitdboClientEntityMappings();
			InitdboDocumentEntityMappings();
			InitdboGovernorateEntityMappings();
			InitdboLicenseEntityMappings();
			InitdboLicenseRequestEntityMappings();
			InitdboLicenseTypeEntityMappings();
			InitdboUserEntityMappings();
			InitdboVersionInfoEntityMappings();
			InitDocumentEntityMappings();
			InitGovernorateEntityMappings();
			InitLicenseEntityMappings();
			InitLicenseRequestEntityMappings();
			InitLicenseTypeEntityMappings();
			InitUserEntityMappings();
			InitVersionInfoEntityMappings();
		}

		/// <summary>Inits ActionEntity's mappings</summary>
		private void InitActionEntityMappings()
		{
			this.AddElementMapping("ActionEntity", @"Licenses-Generator", @"dbo", "Actions", 5, 0);
			this.AddElementFieldMapping("ActionEntity", "Comments", "comments", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("ActionEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("ActionEntity", "RequestId", "RequestId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("ActionEntity", "Type", "type", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("ActionEntity", "UserId", "UserId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
		}

		/// <summary>Inits AddressEntity's mappings</summary>
		private void InitAddressEntityMappings()
		{
			this.AddElementMapping("AddressEntity", @"Licenses-Generator", @"dbo", "Address", 6, 0);
			this.AddElementFieldMapping("AddressEntity", "Address", "address", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AddressEntity", "City", "city", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AddressEntity", "ClientId", "ClientId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("AddressEntity", "Governorate", "governorate", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("AddressEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("AddressEntity", "Zip", "Zip", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits CityEntity's mappings</summary>
		private void InitCityEntityMappings()
		{
			this.AddElementMapping("CityEntity", @"Licenses-Generator", @"dbo", "City", 3, 0);
			this.AddElementFieldMapping("CityEntity", "GovernorateId", "GovernorateId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("CityEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("CityEntity", "Name", "name", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits ClientEntity's mappings</summary>
		private void InitClientEntityMappings()
		{
			this.AddElementMapping("ClientEntity", @"Licenses-Generator", @"dbo", "Client", 3, 0);
			this.AddElementFieldMapping("ClientEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("ClientEntity", "Name", "name", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("ClientEntity", "NationalId", "nationalID", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits dboActionEntity's mappings</summary>
		private void InitdboActionEntityMappings()
		{
			this.AddElementMapping("dboActionEntity", @"Licenses-Generator", @"dbo", "Actions", 5, 0);
			this.AddElementFieldMapping("dboActionEntity", "Comments", "comments", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("dboActionEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("dboActionEntity", "RequestId", "RequestId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("dboActionEntity", "Type", "type", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("dboActionEntity", "UserId", "UserId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
		}

		/// <summary>Inits dboAddressEntity's mappings</summary>
		private void InitdboAddressEntityMappings()
		{
			this.AddElementMapping("dboAddressEntity", @"Licenses-Generator", @"dbo", "Address", 6, 0);
			this.AddElementFieldMapping("dboAddressEntity", "Address", "address", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("dboAddressEntity", "City", "city", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("dboAddressEntity", "ClientId", "ClientId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("dboAddressEntity", "Governorate", "governorate", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("dboAddressEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("dboAddressEntity", "Zip", "Zip", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits dboCityEntity's mappings</summary>
		private void InitdboCityEntityMappings()
		{
			this.AddElementMapping("dboCityEntity", @"Licenses-Generator", @"dbo", "City", 3, 0);
			this.AddElementFieldMapping("dboCityEntity", "GovernorateId", "GovernorateId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("dboCityEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("dboCityEntity", "Name", "name", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits dboClientEntity's mappings</summary>
		private void InitdboClientEntityMappings()
		{
			this.AddElementMapping("dboClientEntity", @"Licenses-Generator", @"dbo", "Client", 3, 0);
			this.AddElementFieldMapping("dboClientEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("dboClientEntity", "Name", "name", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("dboClientEntity", "NationalId", "nationalID", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits dboDocumentEntity's mappings</summary>
		private void InitdboDocumentEntityMappings()
		{
			this.AddElementMapping("dboDocumentEntity", @"Licenses-Generator", @"dbo", "Documents", 5, 0);
			this.AddElementFieldMapping("dboDocumentEntity", "ClientId", "ClientId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("dboDocumentEntity", "Comments", "comments", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("dboDocumentEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("dboDocumentEntity", "Link", "link", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("dboDocumentEntity", "RequestId", "RequestId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
		}

		/// <summary>Inits dboGovernorateEntity's mappings</summary>
		private void InitdboGovernorateEntityMappings()
		{
			this.AddElementMapping("dboGovernorateEntity", @"Licenses-Generator", @"dbo", "Governorate", 2, 0);
			this.AddElementFieldMapping("dboGovernorateEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("dboGovernorateEntity", "Name", "name", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits dboLicenseEntity's mappings</summary>
		private void InitdboLicenseEntityMappings()
		{
			this.AddElementMapping("dboLicenseEntity", @"Licenses-Generator", @"dbo", "License", 5, 0);
			this.AddElementFieldMapping("dboLicenseEntity", "ClientId", "ClientId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("dboLicenseEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("dboLicenseEntity", "IssuedTime", "issued-time", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("dboLicenseEntity", "RequestId", "RequestId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("dboLicenseEntity", "TypeId", "TypeId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
		}

		/// <summary>Inits dboLicenseRequestEntity's mappings</summary>
		private void InitdboLicenseRequestEntityMappings()
		{
			this.AddElementMapping("dboLicenseRequestEntity", @"Licenses-Generator", @"dbo", "License_Request", 6, 0);
			this.AddElementFieldMapping("dboLicenseRequestEntity", "ClientId", "ClientId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("dboLicenseRequestEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("dboLicenseRequestEntity", "IssuedTime", "issued-time", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("dboLicenseRequestEntity", "Status", "status", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("dboLicenseRequestEntity", "TypeId", "TypeId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("dboLicenseRequestEntity", "UserId", "UserId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 5);
		}

		/// <summary>Inits dboLicenseTypeEntity's mappings</summary>
		private void InitdboLicenseTypeEntityMappings()
		{
			this.AddElementMapping("dboLicenseTypeEntity", @"Licenses-Generator", @"dbo", "License_Type", 3, 0);
			this.AddElementFieldMapping("dboLicenseTypeEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("dboLicenseTypeEntity", "TimeTillExpire", "time-till-expire", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("dboLicenseTypeEntity", "Type", "type", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits dboUserEntity's mappings</summary>
		private void InitdboUserEntityMappings()
		{
			this.AddElementMapping("dboUserEntity", @"Licenses-Generator", @"dbo", "User", 5, 0);
			this.AddElementFieldMapping("dboUserEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("dboUserEntity", "Name", "name", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("dboUserEntity", "Password", "password", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("dboUserEntity", "Role", "role", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("dboUserEntity", "Username", "username", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 4);
		}

		/// <summary>Inits dboVersionInfoEntity's mappings</summary>
		private void InitdboVersionInfoEntityMappings()
		{
			this.AddElementMapping("dboVersionInfoEntity", @"Licenses-Generator", @"dbo", "VersionInfo", 3, 4);
			this.AddElementFieldMapping("dboVersionInfoEntity", "AppliedOn", "AppliedOn", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("dboVersionInfoEntity", "Description", "Description", true, "NVarChar", 1024, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("dboVersionInfoEntity", "Version", "Version", false, "BigInt", 0, 19, 0, false, "", null, typeof(System.Int64), 2);
		}

		/// <summary>Inits DocumentEntity's mappings</summary>
		private void InitDocumentEntityMappings()
		{
			this.AddElementMapping("DocumentEntity", @"Licenses-Generator", @"dbo", "Documents", 5, 0);
			this.AddElementFieldMapping("DocumentEntity", "ClientId", "ClientId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("DocumentEntity", "Comments", "comments", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("DocumentEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("DocumentEntity", "Link", "link", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("DocumentEntity", "RequestId", "RequestId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
		}

		/// <summary>Inits GovernorateEntity's mappings</summary>
		private void InitGovernorateEntityMappings()
		{
			this.AddElementMapping("GovernorateEntity", @"Licenses-Generator", @"dbo", "Governorate", 2, 0);
			this.AddElementFieldMapping("GovernorateEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("GovernorateEntity", "Name", "name", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits LicenseEntity's mappings</summary>
		private void InitLicenseEntityMappings()
		{
			this.AddElementMapping("LicenseEntity", @"Licenses-Generator", @"dbo", "License", 5, 0);
			this.AddElementFieldMapping("LicenseEntity", "ClientId", "ClientId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("LicenseEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("LicenseEntity", "IssuedTime", "issued-time", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("LicenseEntity", "RequestId", "RequestId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("LicenseEntity", "TypeId", "TypeId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
		}

		/// <summary>Inits LicenseRequestEntity's mappings</summary>
		private void InitLicenseRequestEntityMappings()
		{
			this.AddElementMapping("LicenseRequestEntity", @"Licenses-Generator", @"dbo", "License_Request", 6, 0);
			this.AddElementFieldMapping("LicenseRequestEntity", "ClientId", "ClientId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("LicenseRequestEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("LicenseRequestEntity", "IssuedTime", "issued-time", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("LicenseRequestEntity", "Status", "status", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("LicenseRequestEntity", "TypeId", "TypeId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("LicenseRequestEntity", "UserId", "UserId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 5);
		}

		/// <summary>Inits LicenseTypeEntity's mappings</summary>
		private void InitLicenseTypeEntityMappings()
		{
			this.AddElementMapping("LicenseTypeEntity", @"Licenses-Generator", @"dbo", "License_Type", 3, 0);
			this.AddElementFieldMapping("LicenseTypeEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("LicenseTypeEntity", "TimeTillExpire", "time-till-expire", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("LicenseTypeEntity", "Type", "type", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"Licenses-Generator", @"dbo", "User", 5, 0);
			this.AddElementFieldMapping("UserEntity", "Id", "id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("UserEntity", "Name", "name", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("UserEntity", "Password", "password", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("UserEntity", "Role", "role", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("UserEntity", "Username", "username", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 4);
		}

		/// <summary>Inits VersionInfoEntity's mappings</summary>
		private void InitVersionInfoEntityMappings()
		{
			this.AddElementMapping("VersionInfoEntity", @"Licenses-Generator", @"dbo", "VersionInfo", 3, 4);
			this.AddElementFieldMapping("VersionInfoEntity", "AppliedOn", "AppliedOn", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("VersionInfoEntity", "Description", "Description", true, "NVarChar", 1024, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("VersionInfoEntity", "Version", "Version", false, "BigInt", 0, 19, 0, false, "", null, typeof(System.Int64), 2);
		}

	}
}
