//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace Licenses_Generator_DBFirst
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Action</summary>
		ActionEntity,
		///<summary>Address</summary>
		AddressEntity,
		///<summary>City</summary>
		CityEntity,
		///<summary>Client</summary>
		ClientEntity,
		///<summary>dboAction</summary>
		dboActionEntity,
		///<summary>dboAddress</summary>
		dboAddressEntity,
		///<summary>dboCity</summary>
		dboCityEntity,
		///<summary>dboClient</summary>
		dboClientEntity,
		///<summary>dboDocument</summary>
		dboDocumentEntity,
		///<summary>dboGovernorate</summary>
		dboGovernorateEntity,
		///<summary>dboLicense</summary>
		dboLicenseEntity,
		///<summary>dboLicenseRequest</summary>
		dboLicenseRequestEntity,
		///<summary>dboLicenseType</summary>
		dboLicenseTypeEntity,
		///<summary>dboUser</summary>
		dboUserEntity,
		///<summary>dboVersionInfo</summary>
		dboVersionInfoEntity,
		///<summary>Document</summary>
		DocumentEntity,
		///<summary>Governorate</summary>
		GovernorateEntity,
		///<summary>License</summary>
		LicenseEntity,
		///<summary>LicenseRequest</summary>
		LicenseRequestEntity,
		///<summary>LicenseType</summary>
		LicenseTypeEntity,
		///<summary>User</summary>
		UserEntity,
		///<summary>VersionInfo</summary>
		VersionInfoEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END


}

